
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (size_t) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[448] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  136,  134,   60,   95,
      101,  134,   85,  133,  134,  128,  121,  122,  131,  129,
      125,  130,   89,  132,   93,   93,  126,   96,  117,  112,
      119,   88,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,  102,  103,   61,   84,  134,  123,  134,  124,    2,
        3,    2,    6,    7,    6,   10,   11,   10,   14,   15,
       14,   18,   19,   18,   22,   23,   22,   26,   27,   26,
       60,  116,    0,  100,    0,  104,    0,    0,  110,  106,

      108,  107,  109,    0,   30,  111,    0,   93,   93,   93,
       93,   93,    0,  127,  118,  115,  120,   87,   86,   90,
       90,   31,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   52,   90,   90,
       90,   90,   90,   90,   90,   79,   90,   90,   90,   90,
       90,   90,   57,   90,   90,   90,   90,   90,   90,   90,
       90,    0,  105,    0,    0,    0,    0,    0,    0,    0,
      114,    0,  100,    0,   99,    0,   99,    0,    0,    0,
       30,   92,   94,  113,   80,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   45,   48,   90,   56,   90,   43,

       46,   90,   90,   90,   90,   90,   90,   81,   90,   90,
       90,   90,   51,   83,   82,   90,   90,   90,   90,   90,
       90,   44,   47,   90,   90,   90,   90,   78,    0,   91,
        0,    0,    0,    0,    0,    0,    0,   98,   97,    0,
        0,    0,    0,    0,    0,    0,   29,   92,   92,   94,
       94,   94,   94,   50,   90,   49,   33,   90,   90,   53,
       90,   72,   90,   40,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   62,   90,   90,   36,
       90,   38,   41,   90,    0,    0,    0,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    0,   34,   90,

       90,   90,   71,   37,    0,   90,   90,   90,   90,   90,
       42,   90,   90,   90,   90,   39,   90,   32,   90,   70,
       59,    4,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   90,   90,   90,    0,    0,   90,
       76,   90,   90,   90,   90,   90,   90,   64,   73,   90,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   74,   35,   90,    0,    0,   54,   66,   67,
       68,   77,   90,   75,   90,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    5,   90,    0,    0,
       90,   90,    8,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   55,    0,   63,   90,   58,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   90,
        0,    0,    0,    0,    0,   13,    0,    0,    9,    0,
       65,   90,   12,   16,    0,    0,    0,    0,   17,   21,
       69,   20,   24,    0,   25,   28,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   20,   24,   20,   20,   20,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       40,   47,   48,   49,   50,   51,   52,   53,   54,   40,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,

       65,   66,   67,   68,   69,   40,   70,   71,   72,   73,
       74,   75,   40,   76,   77,   78,   79,   80,   81,   82,
       83,   40,   84,   85,   86,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[87] =
    {   0,
        1,    1,    2,    3,    3,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    3,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    3,    1,    3,    1,    7,    3,
        6,    6,    6,    6,    6,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[465] =
    {   0,
        0,    0,   84,   85,   86,   87,   88,   89,   90,   91,
       92,   93,   94,   95,   96,  110,  931,  932,  112,  932,
      902,  109,  932,  932,  920,  872,  932,  932,  899,  103,
      932,  102,  932,  106,  149,   67,  898,  932,  897,  896,
      892,  104,   79,   77,  115,   90,  135,  113,    0,   97,
      168,   83,  135,  147,  164,  181,  179,  114,  136,  200,
      141,  932,  932,  932,    0,    0,  932,  826,  932,  932,
      932,  864,  932,  932,  803,  932,  932,  801,  932,  932,
      800,  932,  932,  798,  932,  932,  795,  932,  932,  792,
      137,  778,  142,  932,  233,  932,  795,  794,  932,  932,

      932,  100,  932,  787,    0,  932,  250,  150,  225,  240,
      256,  271,    0,  932,  932,  771,  932,  932,  932,    0,
      111,    0,  176,  178,  123,  191,  215,  200,  208,  207,
      777,  773,  216,  238,  247,  772,  768,  237,  251,  260,
      264,  267,  253,  261,  263,    0,  291,  269,  286,  287,
      295,  300,  290,  293,  759,  749,  304,  310,  321,  314,
      308,  664,  932,  323,  325,  326,  327,  328,  330,  332,
      932,  190,  362,  367,  932,  704,  695,  408,  533,  129,
        0,  377,  366,  932,    0,  332,  344,  333,  327,  354,
      343,  367,  355,  376,    0,    0,  372,    0,  376,    0,

        0,  375,  380,  384,  386,  399,  400,    0,  392,  465,
      397,  404,    0,    0,    0,  407,  401,  404,  408,  427,
      429,    0,    0,  426,  432,  427,  429,    0,  461,  932,
      496,  422,  427,  442,  439,  431,  447,  932,  932,  495,
      449,  437,  445,  441,  437,  462,  932,  465,  469,  486,
      499,  503,  525,    0,  472,    0,    0,  448,  468,  482,
      468,    0,  491,  503,  488,  485,  484,  502,  510,  516,
      514,  502,  512,  518,  530,  547,    0,  532,  534,    0,
      552,    0,    0,  553,  412,  559,  543,  558,  551,  543,
      548,  932,  563,  557,  569,  559,  561,  561,    0,  567,

      566,  569,    0,    0,  573,  564,  566,  583,  576,  589,
        0,  582,  599,  602,  593,    0,  605,    0,  610,    0,
        0,  932,  602,  603,  610,  619,  609,  612,  614,  624,
      617,  611,  627,  411,  616,  612,  621,  632,  630,  636,
        0,  637,  620,  643,  633,  632,  651,    0,    0,  642,
      398,  641,  658,  657,  666,  671,  662,  659,  661,  679,
      679,  396,    0,    0,  666,  670,  680,    0,    0,    0,
        0,    0,  670,    0,  674,  378,  690,  681,  676,  695,
      683,  695,  694,  702,  689,  704,  932,  687,  710,  699,
      717,  717,  932,  707,  722,  724,  727,  725,  371,  723,

      730,  362,  735,    0,  729,  932,  732,    0,  355,  285,
      742,  743,  736,  268,  739,  264,  245,  244,  735,  736,
      236,  228,  227,  189,  745,  932,  185,  166,  932,  148,
      932,  755,  932,  932,  145,  143,  134,  127,  932,  932,
        0,  932,  932,  124,  932,  932,  932,  820,  827,  834,
      841,  848,  855,  862,  869,  876,  879,  881,  888,  895,
      902,  909,  912,  916
    } ;

static yyconst flex_int16_t yy_def[465] =
    {   0,
      447,    1,  448,  448,  449,  449,  450,  450,  451,  451,
      452,  452,  453,  453,  454,  454,  447,  447,  447,  447,
      447,  455,  447,  447,  447,  456,  447,  447,  447,  447,
      447,  447,  447,  447,  447,   35,  447,  447,  447,  447,
      447,  447,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  447,  447,  447,  457,  458,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  455,  447,  459,  447,  447,  460,  447,  447,

      447,  447,  447,  461,  462,  447,  447,   35,  447,  447,
      447,  447,  463,  447,  447,  447,  447,  447,  447,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  464,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  455,  455,  459,  447,  447,  447,  447,  461,  461,
      462,  447,  463,  447,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  464,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  457,  457,

      457,  457,  457,  457,  447,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  457,  457,  457,  447,  447,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  457,  457,  457,  447,  447,  457,  457,  457,
      457,  457,  457,  457,  457,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  457,  447,  447,
      457,  457,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  457,  447,  447,  457,  457,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  457,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  457,  447,  447,  447,  447,  447,  447,  447,  447,
      457,  447,  447,  447,  447,  447,    0,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447
    } ;

static yyconst flex_uint16_t yy_nxt[1019] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       36,   36,   36,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   49,
       49,   52,   49,   53,   54,   55,   49,   56,   57,   58,
       59,   60,   61,   49,   62,   18,   63,   64,   65,   66,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   49,
       52,   49,   53,   54,   55,   49,   56,   57,   58,   59,
       60,   61,   49,   67,   68,   69,   71,   71,   74,   74,
       77,   77,   80,   80,   83,   83,   86,   86,   89,   72,

       72,   75,   75,   78,   78,   81,   81,   84,   84,   87,
       87,   90,   89,   91,   94,   91,  100,  102,  104,  447,
      118,  123,  121,  105,  127,   90,  122,  142,  119,  103,
      101,  135,  178,  106,  131,  155,  132,  156,   91,  446,
       91,  180,  445,  133,  185,  124,  247,   94,  447,  444,
      123,  121,  125,  188,  127,  122,  142,  134,  443,  126,
      442,  135,  178,  440,   95,  107,  157,  108,  108,  108,
      108,  108,  108,  133,  185,  124,  128,  129,  130,  143,
      158,  439,  125,  188,  144,  161,  134,  109,  126,  136,
      110,  137,  145,  146,  147,   94,  157,   95,  111,  112,

      438,  113,  447,  138,  436,  128,  129,  130,  143,  158,
      139,  140,  148,  144,  161,  141,  152,  109,  149,  110,
      186,  145,  146,  153,  147,  154,  187,  111,  112,  150,
      113,  447,  151,  138,  159,   93,  189,  160,  173,  139,
      140,  148,  435,  434,  141,   95,  152,  192,  149,  186,
      190,  433,  153,  193,  154,  187,  194,  197,  150,  430,
      429,  151,  191,  109,  159,  189,  110,  160,  182,  182,
      182,  182,  182,  182,  111,  112,  192,  199,  109,  428,
      190,  110,  193,  426,  198,  194,  197,  202,  174,  111,
      112,  191,  204,  109,  109,  110,  203,  110,  205,  207,

      422,  208,  209,  111,  112,  111,  112,  199,  109,  109,
      110,  210,  110,  198,  206,  213,  202,  216,  111,  112,
      111,  112,  204,  211,  109,  203,  110,  214,  205,  207,
      208,  209,  215,  217,  111,  112,  220,  212,  218,  109,
      210,  110,  221,  206,  213,  224,  219,  216,  225,  111,
      112,  226,  227,  211,  228,  231,  214,  232,  233,  234,
      235,  215,  236,  217,  237,  220,  212,   94,  218,   93,
      421,  221,  173,  254,  224,  219,  255,  417,  225,  256,
      257,  226,  227,  228,  258,  231,  414,  232,  233,  234,
      235,  259,  236,  393,  237,  182,  182,  182,  182,  182,

      182,  260,  254,  261,  250,  265,  255,  251,  256,  257,
      248,  387,  249,  376,  258,  252,  253,   95,  262,  263,
      259,  264,  174,  240,  266,  267,  362,  322,  268,  269,
      270,  260,  261,  271,  250,  265,  251,  273,  274,  275,
      248,  241,  249,  242,  252,  253,  243,  262,  263,  276,
      264,  277,  278,  266,  267,  244,  245,  268,  246,  269,
      270,  279,  271,  280,  281,  282,  273,  283,  274,  275,
      284,  241,  286,  242,  287,  288,  243,  289,  276,  290,
      277,  278,  291,  293,  244,  245,  294,  246,  295,  296,
      297,  279,  298,  280,  281,  282,  283,  300,  248,  284,

      249,  286,  248,  287,  249,  288,  305,  289,  290,  299,
      292,  285,  291,  293,  301,  294,  302,  295,  296,  297,
      230,  303,  298,  272,  250,  304,  300,  251,  248,  306,
      249,  307,  248,  308,  249,  252,  253,  250,  313,  299,
      251,  250,  314,  301,  251,  180,  302,  309,  252,  253,
      303,  310,  252,  253,  250,  304,  251,  311,  306,  312,
      307,  315,  308,  250,  252,  253,  251,  250,  313,  251,
      316,  250,  314,  251,  252,  253,  309,  252,  253,  317,
      310,  252,  253,  318,  319,  320,  311,  321,  312,  323,
      315,  324,  325,  250,  326,  251,  327,  328,  329,  316,

      330,  331,  340,  252,  253,  332,  333,  334,  335,  317,
      336,  337,  318,  319,  341,  320,  342,  321,  338,  323,
      324,  339,  325,  326,  343,  327,  328,  344,  329,  330,
      345,  331,  340,  346,  332,  333,  334,  335,  347,  336,
      337,  348,  349,  341,  350,  353,  342,  338,  351,  352,
      339,  354,  357,  343,  355,  356,  358,  344,  359,  345,
      360,  361,  366,  346,  363,  364,  365,  367,  347,  368,
      348,  369,  349,  370,  350,  353,  371,  351,  352,  372,
      373,  354,  357,  355,  356,  374,  358,  359,  375,  360,
      377,  361,  366,  363,  364,  365,  378,  367,  379,  368,

      380,  369,  370,  381,  239,  382,  371,  383,  372,  373,
      384,  385,  386,  238,  388,  374,  389,  375,  390,  377,
      391,  392,  394,  230,  395,  396,  378,  379,  397,  399,
      380,  398,  400,  381,  382,  401,  383,  402,  403,  384,
      404,  385,  386,  388,  405,  389,  406,  407,  390,  391,
      392,  408,  394,  395,  396,  409,  410,  411,  397,  399,
      398,  412,  400,  413,  416,  401,  402,  415,  403,  404,
      418,  223,  419,  420,  405,  406,  423,  407,  424,  222,
      425,  408,  427,  431,  409,  432,  410,  411,  437,  441,
      201,  412,  200,  413,  416,  196,  415,  195,  184,  180,

      418,  419,  420,  177,  175,  171,  423,  170,  424,  425,
      169,  427,  431,  168,  432,  167,  166,  437,  165,  441,
       70,   70,   70,   70,   70,   70,   70,   73,   73,   73,
       73,   73,   73,   73,   76,   76,   76,   76,   76,   76,
       76,   79,   79,   79,   79,   79,   79,   79,   82,   82,
       82,   82,   82,   82,   82,   85,   85,   85,   85,   85,
       85,   85,   88,   88,   88,   88,   88,   88,   88,   93,
       93,   93,   93,   93,   93,   93,   97,   97,   97,  164,
       97,   97,   97,  120,  120,  120,  162,  162,  172,  172,
      172,  172,  172,  172,  172,  176,  176,  176,  176,  176,

      176,  176,  179,  179,  179,  179,  179,  179,  179,  181,
      163,  181,  181,  181,  181,  181,  183,  183,  229,  117,
      229,  229,  229,  116,  115,  114,   99,   98,   96,   92,
      447,   17,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447
    } ;

static yyconst flex_int16_t yy_chk[1019] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,    3,

        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   19,   22,   19,   30,   32,   34,   36,
       42,   44,   43,   34,   46,   16,   43,   52,   42,   32,
       30,   50,  102,   34,   48,   58,   48,   58,   91,  444,
       91,  180,  438,   48,  121,   45,  180,   93,   36,  437,
       44,   43,   45,  125,   46,   43,   52,   48,  436,   45,
      435,   50,  102,  430,   22,   35,   59,   35,   35,   35,
       35,   35,   35,   48,  121,   45,   47,   47,   47,   53,
       59,  428,   45,  125,   53,   61,   48,   35,   45,   51,
       35,   51,   54,   54,   55,  172,   59,   93,   35,   35,

      427,   35,  108,   51,  424,   47,   47,   47,   53,   59,
       51,   51,   55,   53,   61,   51,   57,   35,   56,   35,
      123,   54,   54,   57,   55,   57,  124,   35,   35,   56,
       35,  108,   56,   51,   60,   95,  126,   60,   95,   51,
       51,   55,  423,  422,   51,  172,   57,  128,   56,  123,
      127,  421,   57,  129,   57,  124,  130,  133,   56,  418,
      417,   56,  127,  109,   60,  126,  109,   60,  107,  107,
      107,  107,  107,  107,  109,  109,  128,  135,  110,  416,
      127,  110,  129,  414,  134,  130,  133,  138,   95,  110,
      110,  127,  140,  109,  111,  109,  139,  111,  141,  142,

      410,  143,  144,  109,  109,  111,  111,  135,  110,  112,
      110,  145,  112,  134,  141,  148,  138,  150,  110,  110,
      112,  112,  140,  147,  111,  139,  111,  149,  141,  142,
      143,  144,  149,  151,  111,  111,  153,  147,  152,  112,
      145,  112,  154,  141,  148,  157,  152,  150,  158,  112,
      112,  159,  160,  147,  161,  164,  149,  165,  166,  167,
      168,  149,  169,  151,  170,  153,  147,  173,  152,  174,
      409,  154,  174,  186,  157,  152,  187,  402,  158,  188,
      189,  159,  160,  161,  190,  164,  399,  165,  166,  167,
      168,  191,  169,  376,  170,  182,  182,  182,  182,  182,

      182,  192,  186,  193,  183,  202,  187,  183,  188,  189,
      182,  362,  182,  351,  190,  183,  183,  173,  194,  197,
      191,  199,  174,  178,  203,  204,  334,  285,  205,  206,
      207,  192,  193,  209,  183,  202,  183,  211,  212,  216,
      182,  178,  182,  178,  183,  183,  178,  194,  197,  217,
      199,  218,  219,  203,  204,  178,  178,  205,  178,  206,
      207,  220,  209,  221,  224,  225,  211,  226,  212,  216,
      227,  178,  232,  178,  233,  234,  178,  235,  217,  236,
      218,  219,  237,  241,  178,  178,  242,  178,  243,  244,
      245,  220,  246,  221,  224,  225,  226,  258,  248,  227,

      248,  232,  249,  233,  249,  234,  264,  235,  236,  255,
      240,  231,  237,  241,  259,  242,  260,  243,  244,  245,
      229,  261,  246,  210,  250,  263,  258,  250,  248,  265,
      248,  266,  249,  267,  249,  250,  250,  251,  272,  255,
      251,  252,  273,  259,  252,  179,  260,  268,  251,  251,
      261,  269,  252,  252,  250,  263,  250,  270,  265,  271,
      266,  274,  267,  253,  250,  250,  253,  251,  272,  251,
      275,  252,  273,  252,  253,  253,  268,  251,  251,  276,
      269,  252,  252,  278,  279,  281,  270,  284,  271,  286,
      274,  287,  288,  253,  289,  253,  290,  291,  293,  275,

      294,  295,  306,  253,  253,  296,  297,  298,  300,  276,
      301,  302,  278,  279,  307,  281,  308,  284,  305,  286,
      287,  305,  288,  289,  309,  290,  291,  310,  293,  294,
      312,  295,  306,  313,  296,  297,  298,  300,  314,  301,
      302,  315,  317,  307,  319,  325,  308,  305,  323,  324,
      305,  326,  329,  309,  327,  328,  330,  310,  331,  312,
      332,  333,  338,  313,  335,  336,  337,  339,  314,  340,
      315,  342,  317,  343,  319,  325,  344,  323,  324,  345,
      346,  326,  329,  327,  328,  347,  330,  331,  350,  332,
      352,  333,  338,  335,  336,  337,  353,  339,  354,  340,

      355,  342,  343,  356,  177,  357,  344,  358,  345,  346,
      359,  360,  361,  176,  365,  347,  366,  350,  367,  352,
      373,  375,  377,  162,  378,  379,  353,  354,  380,  382,
      355,  381,  383,  356,  357,  384,  358,  385,  386,  359,
      388,  360,  361,  365,  389,  366,  390,  391,  367,  373,
      375,  392,  377,  378,  379,  394,  395,  396,  380,  382,
      381,  397,  383,  398,  401,  384,  385,  400,  386,  388,
      403,  156,  405,  407,  389,  390,  411,  391,  412,  155,
      413,  392,  415,  419,  394,  420,  395,  396,  425,  432,
      137,  397,  136,  398,  401,  132,  400,  131,  116,  104,

      403,  405,  407,   98,   97,   92,  411,   90,  412,  413,
       87,  415,  419,   84,  420,   81,   78,  425,   75,  432,
      448,  448,  448,  448,  448,  448,  448,  449,  449,  449,
      449,  449,  449,  449,  450,  450,  450,  450,  450,  450,
      450,  451,  451,  451,  451,  451,  451,  451,  452,  452,
      452,  452,  452,  452,  452,  453,  453,  453,  453,  453,
      453,  453,  454,  454,  454,  454,  454,  454,  454,  455,
      455,  455,  455,  455,  455,  455,  456,  456,  456,   72,
      456,  456,  456,  457,  457,  457,  458,  458,  459,  459,
      459,  459,  459,  459,  459,  460,  460,  460,  460,  460,

      460,  460,  461,  461,  461,  461,  461,  461,  461,  462,
       68,  462,  462,  462,  462,  462,  463,  463,  464,   41,
      464,  464,  464,   40,   39,   37,   29,   26,   25,   21,
       17,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#include <string>
#include "../node/Node.h"
#include "parser.hpp"

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wsign-compare"
#pragma GCC diagnostic ignored "-Wunused-function"
#endif

struct YYLOCATION {
    int l;
    int c;
};
#define YY_EXTRA_TYPE YYLOCATION

void updateLocation(YYLOCATION& loc, const char* s, const size_t len) {
	size_t lastReturn = 0;
	for (size_t i = 0; i < len; i++) {
		if (s[i] == '\n') {
			loc.l++;
			loc.c = 0;
			lastReturn = 0;
		}
	}
	loc.c += (int)(len - lastReturn);
}

#define SAVE_LOC yylloc_param->first_line = yyg->yyextra_r.l; yylloc_param->first_column = yyg->yyextra_r.c; updateLocation(yyg->yyextra_r, yytext, yyleng)
#define TOKEN_STR(t, leftTrim, rightTrim) SAVE_LOC; yylval->string = new std::string(yytext + (size_t)leftTrim, yyleng - (size_t)leftTrim - (size_t)rightTrim); return t
#define TOKEN_VAL(t) SAVE_LOC; yylval->token = t; return t

#define INITIAL 0
#define CBLOCK 1
#define CVAR 2
#define CSTRUCT 3
#define CDEFINE 4
#define CINCLUDE 5
#define CTYPEDEF 6
#define CFUNCTION 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int _line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *yyget_lloc (yyscan_t yyscanner );
    
        void yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state (int _new_state ,yyscan_t yyscanner);
    
    static void yy_pop_state (yyscan_t yyscanner );
    
    static int yy_top_state (yyscan_t yyscanner );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = yyg->yy_c_buf_p - yyg->yytext_ptr;
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 448 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 447 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{ BEGIN(CBLOCK); }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCBLOCK, 0, 1); }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCBLOCK, 0, 5); }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ BEGIN(CVAR); }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCVAR, 0, 1); }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCVAR, 0, 8); }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ BEGIN(CSTRUCT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCSTRUCT, 0, 1); }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCSTRUCT, 0, 11); }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ BEGIN(CDEFINE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCDEFINE, 0, 1); }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCDEFINE, 0, 11); }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ BEGIN(CINCLUDE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCINCLUDE, 0, 1); }
	YY_BREAK
case 20:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCINCLUDE, 0, 12); }
	YY_BREAK
case 21:
YY_RULE_SETUP
{ BEGIN(CTYPEDEF); }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCTYPEDEF, 0, 1); }
	YY_BREAK
case 24:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCTYPEDEF, 0, 12); }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ BEGIN(CFUNCTION); }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ yymore(); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
{ TOKEN_STR(TCFUNCTION, 0, 1); }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ BEGIN(INITIAL); TOKEN_STR(TCFUNCTION, 0, 13); }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
TOKEN_VAL(TEND);
	YY_BREAK
case 30:
YY_RULE_SETUP
TOKEN_VAL(TEND);
	YY_BREAK
case 31:
YY_RULE_SETUP
TOKEN_VAL(TAS);
	YY_BREAK
case 32:
YY_RULE_SETUP
TOKEN_VAL(TTHROW);
	YY_BREAK
case 33:
YY_RULE_SETUP
TOKEN_VAL(TCOPY);
	YY_BREAK
case 34:
YY_RULE_SETUP
TOKEN_VAL(TCATCH);
	YY_BREAK
case 35:
YY_RULE_SETUP
TOKEN_VAL(TDESTROY);
	YY_BREAK
case 36:
YY_RULE_SETUP
TOKEN_VAL(TTRUE);
	YY_BREAK
case 37:
YY_RULE_SETUP
TOKEN_VAL(TFALSE);
	YY_BREAK
case 38:
YY_RULE_SETUP
TOKEN_VAL(TVOID);
	YY_BREAK
case 39:
YY_RULE_SETUP
TOKEN_VAL(TSTACK);
	YY_BREAK
case 40:
YY_RULE_SETUP
TOKEN_VAL(THEAP);
	YY_BREAK
case 41:
YY_RULE_SETUP
TOKEN_VAL(TWEAK);
	YY_BREAK
case 42:
YY_RULE_SETUP
TOKEN_VAL(TLOCAL);
	YY_BREAK
case 43:
YY_RULE_SETUP
TOKEN_VAL(TTYPEI32);
	YY_BREAK
case 44:
YY_RULE_SETUP
TOKEN_VAL(TTYPEU32);
	YY_BREAK
case 45:
YY_RULE_SETUP
TOKEN_VAL(TTYPEF32);
	YY_BREAK
case 46:
YY_RULE_SETUP
TOKEN_VAL(TTYPEI64);
	YY_BREAK
case 47:
YY_RULE_SETUP
TOKEN_VAL(TTYPEU64);
	YY_BREAK
case 48:
YY_RULE_SETUP
TOKEN_VAL(TTYPEF64);
	YY_BREAK
case 49:
YY_RULE_SETUP
TOKEN_VAL(TTYPECHAR);
	YY_BREAK
case 50:
YY_RULE_SETUP
TOKEN_VAL(TTYPEBOOL);
	YY_BREAK
case 51:
YY_RULE_SETUP
TOKEN_VAL(TTYPEPTR);
	YY_BREAK
case 52:
YY_RULE_SETUP
TOKEN_VAL(TIF);
	YY_BREAK
case 53:
YY_RULE_SETUP
TOKEN_VAL(TELSE);
	YY_BREAK
case 54:
YY_RULE_SETUP
TOKEN_VAL(TIFVALID);
	YY_BREAK
case 55:
YY_RULE_SETUP
TOKEN_VAL(TELSEEMPTY);
	YY_BREAK
case 56:
YY_RULE_SETUP
TOKEN_VAL(TFOR);
	YY_BREAK
case 57:
YY_RULE_SETUP
TOKEN_VAL(TTO);
	YY_BREAK
case 58:
YY_RULE_SETUP
TOKEN_VAL(TTOREVERSE);
	YY_BREAK
case 59:
YY_RULE_SETUP
TOKEN_VAL(TWHILE);
	YY_BREAK
case 60:
YY_RULE_SETUP
SAVE_LOC; 
	YY_BREAK
case 61:
YY_RULE_SETUP
TOKEN_STR(TIDENTIFIER, 0, 0);
	YY_BREAK
case 62:
YY_RULE_SETUP
TOKEN_VAL(TTHIS);
	YY_BREAK
case 63:
YY_RULE_SETUP
TOKEN_VAL(THEAPTHIS);
	YY_BREAK
case 64:
YY_RULE_SETUP
TOKEN_VAL(TPARENT);
	YY_BREAK
case 65:
YY_RULE_SETUP
TOKEN_VAL(THEAPPARENT);
	YY_BREAK
case 66:
YY_RULE_SETUP
TOKEN_VAL(TINCLUDE);
	YY_BREAK
case 67:
YY_RULE_SETUP
TOKEN_VAL(TISEMPTY);
	YY_BREAK
case 68:
YY_RULE_SETUP
TOKEN_VAL(TISVALID);
	YY_BREAK
case 69:
YY_RULE_SETUP
TOKEN_VAL(TGETVALUE);
	YY_BREAK
case 70:
YY_RULE_SETUP
TOKEN_VAL(TVALID);
	YY_BREAK
case 71:
YY_RULE_SETUP
TOKEN_VAL(TEMPTY);
	YY_BREAK
case 72:
YY_RULE_SETUP
TOKEN_VAL(TENUM);
	YY_BREAK
case 73:
YY_RULE_SETUP
TOKEN_VAL(TSWITCH);
	YY_BREAK
case 74:
YY_RULE_SETUP
TOKEN_VAL(TDEFAULT);
	YY_BREAK
case 75:
YY_RULE_SETUP
TOKEN_VAL(TPACKAGE);
	YY_BREAK
case 76:
YY_RULE_SETUP
TOKEN_VAL(TIMPORT);
	YY_BREAK
case 77:
YY_RULE_SETUP
TOKEN_VAL(TNULLPTR);	
	YY_BREAK
case 78:
YY_RULE_SETUP
TOKEN_VAL(TBOOLXOR);
	YY_BREAK
case 79:
YY_RULE_SETUP
TOKEN_VAL(TBOOLOR);
	YY_BREAK
case 80:
YY_RULE_SETUP
TOKEN_VAL(TBOOLAND);
	YY_BREAK
case 81:
YY_RULE_SETUP
TOKEN_VAL(TBOOLNOT);
	YY_BREAK
case 82:
YY_RULE_SETUP
TOKEN_VAL(TBOOLSHR);
	YY_BREAK
case 83:
YY_RULE_SETUP
TOKEN_VAL(TBOOLSHL);
	YY_BREAK
case 84:
YY_RULE_SETUP
TOKEN_VAL(TUNDERSCORE);
	YY_BREAK
case 85:
YY_RULE_SETUP
TOKEN_VAL(THASH);
	YY_BREAK
case 86:
YY_RULE_SETUP
TOKEN_VAL(TQUESTIONCOLON);
	YY_BREAK
case 87:
YY_RULE_SETUP
TOKEN_VAL(TQUESTIONDOT);
	YY_BREAK
case 88:
YY_RULE_SETUP
TOKEN_VAL(TQUESTION);
	YY_BREAK
case 89:
YY_RULE_SETUP
TOKEN_VAL(TDOT);
	YY_BREAK
case 90:
YY_RULE_SETUP
TOKEN_STR(TIDENTIFIER, 0, 0);
	YY_BREAK
case 91:
YY_RULE_SETUP
TOKEN_STR(TQUOTEDIDENTIFIER, 1, 1);
	YY_BREAK
case 92:
YY_RULE_SETUP
TOKEN_STR(TDOUBLE, 0, 0);
	YY_BREAK
case 93:
YY_RULE_SETUP
TOKEN_STR(TINTEGER, 0, 0);
	YY_BREAK
case 94:
YY_RULE_SETUP
TOKEN_STR(TINTEGER, 0, 0);
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
TOKEN_VAL(TEND);
	YY_BREAK
case 96:
YY_RULE_SETUP
TOKEN_VAL(TEND);
	YY_BREAK
case 97:
YY_RULE_SETUP
TOKEN_STR(TCHAR, 1, 1);
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
TOKEN_STR(TCHAR, 1, 1);
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
TOKEN_STR(TCHAR, 1, 1);
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
TOKEN_STR(TSTRING, 1, 1);
	YY_BREAK
case 101:
YY_RULE_SETUP
TOKEN_VAL(TEXCLAIM);
	YY_BREAK
case 102:
YY_RULE_SETUP
TOKEN_VAL(TLBRACKET);
	YY_BREAK
case 103:
YY_RULE_SETUP
TOKEN_VAL(TRBRACKET);
	YY_BREAK
case 104:
YY_RULE_SETUP
TOKEN_VAL(TAND);
	YY_BREAK
case 105:
YY_RULE_SETUP
TOKEN_VAL(TOR);
	YY_BREAK
case 106:
YY_RULE_SETUP
TOKEN_VAL(TPLUSPLUS);
	YY_BREAK
case 107:
YY_RULE_SETUP
TOKEN_VAL(TMINUSMINUS);
	YY_BREAK
case 108:
YY_RULE_SETUP
TOKEN_VAL(TPLUSEQUAL);
	YY_BREAK
case 109:
YY_RULE_SETUP
TOKEN_VAL(TMINUSEQUAL);
	YY_BREAK
case 110:
YY_RULE_SETUP
TOKEN_VAL(TMULEQUAL);
	YY_BREAK
case 111:
YY_RULE_SETUP
TOKEN_VAL(TDIVEQUAL);
	YY_BREAK
case 112:
YY_RULE_SETUP
TOKEN_VAL(TEQUAL);
	YY_BREAK
case 113:
YY_RULE_SETUP
TOKEN_VAL(TCPEQ);
	YY_BREAK
case 114:
YY_RULE_SETUP
TOKEN_VAL(TCPNE);
	YY_BREAK
case 115:
YY_RULE_SETUP
TOKEN_VAL(TCEQ);
	YY_BREAK
case 116:
YY_RULE_SETUP
TOKEN_VAL(TCNE);
	YY_BREAK
case 117:
YY_RULE_SETUP
TOKEN_VAL(TCLT);
	YY_BREAK
case 118:
YY_RULE_SETUP
TOKEN_VAL(TCLE);
	YY_BREAK
case 119:
YY_RULE_SETUP
TOKEN_VAL(TCGT);
	YY_BREAK
case 120:
YY_RULE_SETUP
TOKEN_VAL(TCGE);
	YY_BREAK
case 121:
YY_RULE_SETUP
TOKEN_VAL(TLPAREN);
	YY_BREAK
case 122:
YY_RULE_SETUP
TOKEN_VAL(TRPAREN);
	YY_BREAK
case 123:
YY_RULE_SETUP
TOKEN_VAL(TLBRACE);
	YY_BREAK
case 124:
YY_RULE_SETUP
TOKEN_VAL(TRBRACE);
	YY_BREAK
case 125:
YY_RULE_SETUP
TOKEN_VAL(TCOMMA);
	YY_BREAK
case 126:
YY_RULE_SETUP
TOKEN_VAL(TCOLON);
	YY_BREAK
case 127:
YY_RULE_SETUP
TOKEN_VAL(TCOLONEQUAL);
	YY_BREAK
case 128:
YY_RULE_SETUP
TOKEN_VAL(TQUOTE);
	YY_BREAK
case 129:
YY_RULE_SETUP
TOKEN_VAL(TPLUS);
	YY_BREAK
case 130:
YY_RULE_SETUP
TOKEN_VAL(TMINUS);
	YY_BREAK
case 131:
YY_RULE_SETUP
TOKEN_VAL(TMUL);
	YY_BREAK
case 132:
YY_RULE_SETUP
TOKEN_VAL(TDIV);
	YY_BREAK
case 133:
YY_RULE_SETUP
TOKEN_VAL(TMOD);
	YY_BREAK
case 134:
YY_RULE_SETUP
TOKEN_STR(TINVALID, 0, 0);
	YY_BREAK
case 135:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CBLOCK):
case YY_STATE_EOF(CVAR):
case YY_STATE_EOF(CSTRUCT):
case YY_STATE_EOF(CDEFINE):
case YY_STATE_EOF(CINCLUDE):
case YY_STATE_EOF(CTYPEDEF):
case YY_STATE_EOF(CFUNCTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 448 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 448 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 447);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) yyalloc(new_size ,yyscanner );

		else
			yyg->yy_start_stack = (int *) yyrealloc((void *) yyg->yy_start_stack,new_size ,yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

    static int yy_top_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

