root := heap fillLayout() as #element
menuScene := heap nauScene3dElement()
menuElement := heap fillLayout() as #element
fieldScene := heap nauScene3dElement()
fieldElement := heap fillLayout() as #element
fieldBuyElement := heap fillLayout()
forestScene := heap nauScene3dElement()
forestElement := heap fillLayout() as #element
forestBuyElement := heap fillLayout()